### ISSUE TITLE
Library cannot be loaded on Java8 JVMs

### ISSUE THREAD

**Issue by vtkstef** [Password4j/password4j#112]
**Describe the bug**
Library cannot be loaded on Java8 JVMs

**To Reproduce**
attempt to use the library on java 8

```
ERROR java.lang.UnsupportedClassVersionError:
com/password4j/jca/providers/Password4jProvider has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Expected behavior**
Java8 JVMs should be able to load Password4j

**Environment:**
 - OS: Mac 0S
 - JDK: Zulu 8.0.372
 - Version: 1.7.0

**Additional context**

**Comment by firaja** [comment]
Hello @vtkstef,

you are using [password4j-jca](https://github.com/Password4j/password4j-jca) which requires Java 9+.
See the [installation requirements](https://github.com/Password4j/password4j-jca#installation).

**Comment by vtkstef** [comment]
Bummer! Thanks. A lot of enterprises still use Java 8 and this preclude us from adopting your  excellent implementation
