### ISSUE TITLE
Bad Shift in Bcrypt cryptRaw

### ISSUE THREAD

**Issue by david-hawley** [Password4j/password4j#114]
https://github.com/Password4j/password4j/blob/bf3a6017f06a5abc6754e35f1c0abe7731e7bb71/src/main/java/com/password4j/BcryptFunction.java#L768

When `logRounds` is 31 (the max allowed value), this shift results in a negative number. Effectively the rounds is set to 0.

**Comment by firaja** [comment]
Hi @david-hawley 

actually the maximum allowed is 30 and not 31.

> https://github.com/Password4j/password4j/blob/bf3a6017f06a5abc6754e35f1c0abe7731e7bb71/src/main/java/com/password4j/BcryptFunction.java#L766-L767
> 
> When `logRounds` is 31 (the max allowed value), this shift results in a negative number. Effectively the rounds is set to 0.

**Comment by david-hawley** [comment]
@firaja that BadParametersException check is greater than 31, not greater or equals. 
But just try it. Set the hash.bcrypt.rounds=31 and measure how long it takes. Or use a debugger. `rounds` is set to `-2147483648`. 

![image](https://user-images.githubusercontent.com/784743/234679950-9a97e844-1277-4d3d-89be-7ecbfb9c4d3f.png)

**Comment by firaja** [comment]
@david-hawley sorry I completely misunderstood your point.

I think that converting `rounds` from `int` to `long` should do the trick.

**Comment by david-hawley** [comment]
Converting to long would fix it. I have a draft PR for that. Given the possible issues below I wonder if changing the limit to 30 would be better. 

One of the tests in `BcryptFunctionTest.genSaltGeneratesCorrectSaltPrefix` is now impractical to run (unless you want the test to take 2 days).  

If anyone were currently using 31 rounds this fix is going to cause issues. 
1. Checking existing passwords is going to take a very long time (days). As will making new passwords. 
2. When that time passes the check will fail against passwords encoded with the previous version. 

I am not sure how/if the PR should have any unit tests for this 31 case.

**Comment by firaja** [comment]
> Converting to long would fix it. I have a draft PR for that. Given the possible issues below I wonder if changing the limit to 30 would be better.
> 
> One of the tests in `BcryptFunctionTest.genSaltGeneratesCorrectSaltPrefix` is now impractical to run (unless you want the test to take 2 days).
> 
> If anyone were currently using 31 rounds this fix is going to cause issues.
> 
> 1. Checking existing passwords is going to take a very long time (days). As will making new passwords.
> 2. When that time passes the check will fail against passwords encoded with the previous version.
> 
> I am not sure how/if the PR should have any unit tests for this 31 case.

In this case a unit test is not doable and just checking the parameters encoded in the hash wouldn't add any additional level of correctness that the other tests are already giving.

Even if there may be cases of projects using 31, their hashes would be not correct. A migration approach would be to use version 1.7.0 and update the hash to 30 log rounds. After that install 1.7.1 and migrate back to 31 log rounds. But I think that using 31 log rounds is not usable for any system.

**Comment by codylerum** [comment]
Should this be closed?

**Comment by david-hawley** [comment]
@codylerum The fix was merged. I don't know the close policy for this project. It hasn't been released yet. 

I hope no one is unintentionally using 31 rounds. Mitigation is going to be tricky without something to assist.

**Comment by firaja** [comment]
Hello @codylerum @david-hawley,

this fix is now present in 1.7.1
