### ISSUE TITLE
There is no option to disable console printBanner.

### ISSUE THREAD

**Issue by drnkwati** [Password4j/password4j#135]
There is currently no way of disabling the printBanner from showing in console without using a properties file.
**To Reproduce**
Instantiate password4j classes without a  psw4j.properties. 
**Expected behavior**
A way of disabling the printBanner without creating a psw4j.properties. 

**Environment:**
 - OS: MACOS 13
 - JDK 17
![image](https://github.com/Password4j/password4j/assets/7881511/0c9f6455-1cae-4aa4-8571-f08331ebb5a4)

thanks!

**Comment by firaja** [comment]
Hi @drnkwati,

can you give me some context on your application? If you are unable to create a .properties file then an environment variable would be more feasible?

**Comment by drnkwati** [comment]
Hi @firaja 
Is the printBanner a necessity? 
Why not disable it by default.
Regarding context, I am testing in a console app. I usually develop my applications as reusable components or libraries. Password4j is a dependency. 
Some developers like myself generally prefer configurations using classes and annotations instead of xml files.

**Comment by firaja** [comment]
There's no instantiation as it is processed by the classloader, so it's quite hard to do it with an API that makes sense.
If you are developing a console application you can still pack the .properties file in your jar.
The banner, in addition to helping advertise the project, shows which algorithms are supported by the current JDK (_e.g._ not all the HmacSHA algorithms are equally supported by vendors).
