### ISSUE TITLE
stdout polluted with friendly message

### ISSUE THREAD

**Issue by constructivetim** [Password4j/password4j#136]
ho do i stop this appearing every time I start java?

|
    |                Password4j
    + \             .: v1.7.3 :.
    \\.G_.*=.
     `(H'/.\|        ✅ Argon2
      .>' (_--.      ✅ scrypt
   _=/d   ,^\        ✅ bcrypt
 ~~ \)-'-'           ✅ PBKDF2-SHA1/SHA384/SHA512/256/SHA256/SHA512/224/SHA224/SHA512
    / |
    '  '
 ⭐ If you enjoy Password4j, please star the project at https://github.com/Password4j/password4j
 🪲  Report any issue at https://github.com/Password4j/password4j/issues

**Comment by firaja** [comment]
Hi @constructivetim you can disable the startup banner by setting `global.banner=false` in your `psw4j.properties`

Here the doc for the property https://github.com/Password4j/password4j/wiki/Properties#globalbanner-boolean

**Comment by constructivetim** [comment]
thanks very much
