### ISSUE TITLE
Additional Exception Handling for Restricted Environments

### ISSUE THREAD

**Issue by terryquigleysas** [Password4j/password4j#153]
**Describe the bug**
We are looking to use password4j in an application that has a strict security policy, meaning that a static initializer will prevent the Password class from loading. We would like to add additional exception handling to allow password4j to be usable in this environment.

**To Reproduce**
Run password4j with a heavily restricted security policy - e.g. no FilePermissions.

**Expected behavior**
Password4j should be usable even when no access to psw4j.properties due to a restrictive security policy.

**Environment:**
 - OS: [All]
 - JDK [OracleJDK 11 and 17]
 - Version [1.7.3, 1.8.1]

**Additional context**
We have a fix ready. I will supply a PR.

**Comment by firaja** [comment]
Thank you for your support to the project. I'm going to release 1.8.2 in 1-2 days and this will be part of the package.

**Comment by terryquigleysas** [comment]
@firaja Great news. Thank you!
