### ISSUE TITLE
"Global salt length is not defined in properties file." message repeatedly logged in restricted environments

### ISSUE THREAD

**Issue by dancristiancecoi** [Password4j/password4j#157]
**Describe the bug**
This issue builds on top of https://github.com/Password4j/password4j/issues/153. 

Every time we call the hash method of the PBKDF2 hashing function, the following message gets logged:

_Global salt length is not defined in properties file. Default value is used (64). Please set property global.salt.length in your psw4j.properties file._

We would like to suppress/remove this logging message when running in environments that don't use the psw4j.properties file.

**To Reproduce**
Run password4j without supplying psw4j.properties file and call PBKDF2's hash method

**Expected behavior**
Ideally either completely suppress this message or not log it at WARN level when running in restricted environments

**Comment by firaja** [comment]
Hi @dancristiancecoi,

just to have a bit of context: is the problem that the log appears too many times, or is it that it appears even just once?

**Comment by firaja** [comment]
Hi @dancristiancecoi,

`HashBuilder#addRandomSalt()` implies a configuration file.
Unfortunately, I haven't updated the wiki yet, which mentions that a 64 byte salt will be generated without referencing the configuration file (old behavior).

So every time you use `Password.hash(...).addRandomSalt()....` the library checks the in-memory version of the psw4j.properties file.

If you use instead `HashBuilder#addRandomSalt(int)` the configurations in the files are simply overridden.

For example
```java
Password.hash(plainText).addRandomSalt(64).withPBKDF2();
```

If you are in a restricted environment, I strongly suggest to specify all the parameters needed in the hashing process.
```java
// parameters taken from OWASP
PBKDF2Function pbkdf2 = PBKDF2Function.getInstance(Hmac.SHA256, 600_000, 256);
Hash hash = Password.hash(plainText).addRandomSalt(128).with(pbkdf2);
```

**Comment by dancristiancecoi** [comment]
Thanks for getting back to me @firaja ! 

That makes sense as I am using the compressed pbkdf2 function. 

I am away for the rest of the week but will test your suggestions when I'm back. Thanks again!

**Comment by dancristiancecoi** [comment]
Just to confirm that your suggestion worked.

Using the following code removed the log messages:
` Password.hash(passwordBuffer).addRandomSalt(64).with(hashingFunction).getResult()`

Thanks again!
