### ISSUE TITLE
Verify function always return true, am I doing wrong?

### ISSUE THREAD

**Issue by RasyiidWho** [Password4j/password4j#16]
**Describe the bug**
This issue happen in random device, verify function Password.check(password, hash).withBCrypt() always return true, even with wrong password.

**To Reproduce**
App with login (username & password) system.

**Expected behavior**
Verify function return correct value.

**Environment:**
 - OS: Windows
 - IDE: Android Studio 4.2 Canary 12 

 - Device spec with working Verify function
![image](https://user-images.githubusercontent.com/19422415/94103405-cdb82600-fe5e-11ea-8fd1-77967947e3c3.png)

 -  Device spec with Verify function always return true
![image](https://user-images.githubusercontent.com/19422415/94103374-c002a080-fe5e-11ea-8381-607eaeb409be.png)

 - Other
![image](https://user-images.githubusercontent.com/19422415/94101724-a5c6c380-fe5a-11ea-8f7f-4d9bd1cd3cca.png)
![image](https://user-images.githubusercontent.com/19422415/94101745-b4ad7600-fe5a-11ea-8d6c-2df9440c62fe.png)

**Additional context**
Here's my code and result:

Code
![image](https://user-images.githubusercontent.com/19422415/94103477-ff30f180-fe5e-11ea-8784-3fcd5e775b40.png)

Result
![image](https://user-images.githubusercontent.com/19422415/94103750-8c744600-fe5f-11ea-81a1-4f7d109b1d34.png)

Thankyou firaja :D

**Comment by firaja** [comment]
Hi @RasyiidWho,

what happens if you do something like this?
```java
Hash hash = Password.hash("uwu").withBCrypt();
boolean verified = Password.check("wrong password", hash.getResult()).withBCrypt();

if(verified)
{
    // Print "OK"
} 
else
{
    // Print "KO"
}

```

What are the configurations in your `psw4j.properties` file?
Do you have the same issue on a classic Java application or just on Android?
Thanks

**Comment by RasyiidWho** [comment]
> what happens if you do something like this?

 I have tried using this code 

```
Hash hash = Password.hash("uwu").withBCrypt();
boolean verified = Password.check("wrong password", hash.getResult()).withBCrypt();

if(verified)
{
    // Print "OK"
} 
else
{
    // Print "KO"
}
```

but still gives me same result (always return true)

> What are the configurations in your psw4j.properties file?

I'm on Android Studio IDE with gradle as a build tool. I've try to put `psw4j.properties` in classpath, but it's seems library not picking up the properties file. Trying to use `gradle.properties ` and set jvm argument `org.gradle.jvmargs=-Dpsw4j.configuration=G\:\\AndroidStudioProject\\ROUTEKNIS\\psw4j.properties` but still the same (not picking up the properties file). So for now it uses default properties

> Do you have the same issue on a classic Java application or just on Android?

I tried your code in NetBeans IDE, and it's working well, so it only happen on Android, even not all Android phone have this issue

![image](https://user-images.githubusercontent.com/19422415/94223202-8773cd00-ff19-11ea-87c5-dbb747f364a6.png)

**Comment by firaja** [comment]
On which Android devices is working? Do they have something in common?

**Comment by RasyiidWho** [comment]
> On which Android devices is working? Do they have something in common?

I have test in on 3 phones. There are 2 physical device (android 10 & 6) and 1 emulator device (android 10). And this problem only happend in 1 physical device that have android 10.

**Comment by firaja** [comment]
I've tried the following in a `build.gradle` file

```gradle
plugins {
    id 'java'
    id 'application'
}

applicationDefaultJvmArgs = ["-Dpsw4j.configuration=/path/to/file.properties"]

```

And the file is correctly read on Unix systems.

On Windows I suggest to to not escape `:`
You can use
`G:\\AndroidStudioProject\\ROUTEKNIS\\psw4j.properties`
or
`G:/AndroidStudioProject/ROUTEKNIS/psw4j.properties`

You should also check on your device if there's some known problem with the generation of random bytes.
You can check with the following property if the problem occurs again:
```properties
global.random.strong=true
```
This is always recommended if your JVM supports `SecureRandom.getInstanceStrong()` and it points to a non-blocking source of entropy, otherwise you may experience huge performance drops.


Also check if this method returns every time different results:
```java
SaltGenerator.generate();
```
