### ISSUE TITLE
Function renaming

### ISSUE THREAD

**Issue by firaja** [Password4j/password4j#36]
Some classes and function use bad naming conventions like `BCryptFunction` instead of `BcryptFunction` or `withSCrypt()` instead of `withScrypt()`.

**Comment by Umang228** [comment]
Can I work on the issue.....

**Comment by firaja** [comment]
Hi @Umang228,

this [commit](https://github.com/Password4j/password4j/commit/a3941abfec0964a645383e93a979d89b7d9f684f) already solved the problem. 

But thank you for your interest on the project!
