### ISSUE TITLE
Typo on wiki 

### ISSUE THREAD

**Issue by mauro-pine** [Password4j/password4j#59]
**Describe the bug**
just to let you know - while playing with your implementation I found some typos on your wiki

BcryptFunction on wiki vs BCryptFunction in source
ScryptFunction on wiki vs SCryptFunction &  findWorkFactorForSCrypt & findResourcesForSCrypt

**Comment by firaja** [comment]
Hi @mauro-pine ,

sorry for the late answer!
The documentation is aligned with version [1.6.0](https://github.com/Password4j/password4j/releases/tag/1.6.0), which comes out today with a huge delay 😞
