### ISSUE TITLE
SecureString.toString exposes password length

### ISSUE THREAD

**Issue by nkiesel** [Password4j/password4j#6]
`SecureString.toString` returns a masked value like `[***]`.  However, the number of `*` returned is taken from the number of characters of the contained password, exposing it's length.  I suggest to always return the same constant (e.g. `[*****]`) instead.

**Comment by firaja** [comment]
Even if `#lenght()` exposes the length of the password, hiding the numbers of the characters in `#toString()` may prevent data leaks; a case example is a developer that accidentally uses a `SecureString`  object in a method that calls `#toString()` on some of its arguments (e.g. `PrintStream`).

Thank you @nkiesel

**Comment by firaja** [comment]
Solved in #7
