### ISSUE TITLE
Remove this unnecessary cast to "xxx".

### ISSUE THREAD

**Issue by firaja** [Password4j/password4j#75]
From [sonarcloud report](https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1905&types=CODE_SMELL&id=Password4j_password4j): Casting may be required to distinguish the method to call in the case of overloading
### Noncompliant
```java
public void example() {
  for (Foo obj : (List<Foo>) getFoos()) {  // Noncompliant; cast unnecessary because List<Foo> is what's returned
    //...
  }
}

public List<Foo> getFoos() {
  return this.foos;
}
```

### Compliant
```java
public void example() {
  for (Foo obj : getFoos()) {
    //...
  }
}

public List<Foo> getFoos() {
  return this.foos;
}
```

**Comment by dylanmora** [comment]
Can I be assigned to this issue @firaja

**Comment by dylanmora** [comment]
#77
