### ISSUE TITLE
Move assertions into separate method or use assertThrows or try-catch instead.

### ISSUE THREAD

**Issue by firaja** [Password4j/password4j#76]
From [sonarcloud report](https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS5777&id=Password4j_password4j&open=AYFxmnZyGbWoEcWnZwfZ):

When testing exception via `@Test` annotation, having additional assertions inside that test method can be problematic because any code after the raised exception will not be executed. It will prevent you to test the state of the program after the raised exception and, at worst, make you misleadingly think that it is executed.

You should consider moving any assertions into a separate test method where possible, or using [org.junit.Assert.assertThrows](https://github.com/junit-team/junit4/wiki/Exception-testing#using-assertthrows-method) instead.

Alternatively, you could use [try-catch idiom](https://github.com/junit-team/junit4/wiki/Exception-testing#trycatch-idiom) for JUnit version < 4.13 or if your project does not support lambdas.

### Compliant 
```java
// This test correctly fails.
@Test
public void testToString() {
    Object obj = get();
    Assert.assertThrows(IndexOutOfBoundsException.class, () -> obj.toString());
    Assert.assertEquals(0, 1);
}
```

**Comment by GaneshanNT** [comment]
Hey @firaja ,  I will work this issue

```
@Test
    public void testPBKDF2WrongCheck2()
    {
        // GIVEN
        String hashed = "$3$42949672960256$YWJj$/WTQfTTc8Hg8GlplP0LthpgdElUG+I3MyuvK8MI4MnQ=";
        String badHash = "$342949672960256$YWJj$/WTQfTTc8Hg8GlplP0LthpgdElUG+I3MyuvK8MI4MnQ=";
        String userSubmittedPassword = "password";

        // WHEN
        HashingFunction strategy = CompressedPBKDF2Function.getInstanceFromHash(hashed);

        // THEN
        BadParametersException ex = assertThrows(BadParametersException.class,()->{
            strategy.check(userSubmittedPassword, badHash);
        });
        assertEquals("`" + hashed + "` is not a valid hash",ex.getMessage());
        Assert.assertTrue(strategy.check(userSubmittedPassword, badHash));
    }
```

will it be fine to test expected exception like above code

**Comment by firaja** [comment]
Hello @GaneshanNT 

sounds good to me, thank you!
