### ISSUE TITLE
Remove logging functionalities

### ISSUE THREAD

**Issue by firaja** [Password4j/password4j#82]
The project doesn't really need a logging system that could interact negatively with the logging system of the target environment.

**Comment by ParthasarathiMahana** [comment]
@firaja please describe more about the issue, I will like to contribute.

**Comment by firaja** [comment]
Hi @ParthasarathiMahana,

it is needed to remove every instance of slf4j (dependency and code) because logging is not required.

**Comment by BuZZ-dEE** [comment]
@firaja why is it not planned?
