### ISSUE TITLE
Add banner

### ISSUE THREAD

**Issue by firaja** [Password4j/password4j#83]
Add banner to involve more people with the project

**Comment by lordofpipes** [comment]
No way to disable without a system property? And it uses STDOUT instead of STDERR?

**Comment by firaja** [comment]
> No way to disable without a system property? And it uses STDOUT instead of STDERR?
> 
> **Edit:** For those just wishing to disable it, one good way to set the property is to include a resource file:
> 
> > `src/main/resources/psw4j.properties`
> > ```ini
> > global.banner=false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (Removes stdout messages from Password4J)

STDERR is for errors.
The property is documented in the wiki.
