### ISSUE TITLE
Configurable salt length

### ISSUE THREAD

**Issue by res13** [Password4j/password4j#97]
**Is your feature request related to a problem? Please describe.**
In a situation where there are different remote java repositories for the same company, I would like to standardize all the password hashing algorithms among them. My goal is that all of them use password4j. I manage the property file (psw4j.properties) and they manage their code. Currently, the salt length can only be changed via code (not via properties), which can lead to inconsistencies between repositories.

**Describe the solution you'd like**
I would like to be able to have the salt length a configurable property like `global.salt.length=16` which is used in the class `SaltGenerator`.

**Describe alternatives you've considered**
* I could use the default (hardcoded) length of 64 but that is a bit too long for my taste.
* I would need to make sure that each remote dev team uses the same length by clear communication and in-depth code review (which is a lot more work for me).

**Additional context**
great library by the way, huge fan!

**Comment by firaja** [comment]
Hello @res13,

I put this request in the roadmap for 1.6.4.

If you want you can create a pull request with that feature. I will be happy to review it.
If you need help you can ask here, but you can follow what has been done for [PepperGenerator#get()](https://github.com/Password4j/password4j/blob/c898bac51e712ae92ce9f8b5ec3c75f88370832e/src/main/java/com/password4j/PepperGenerator.java#L92).

**Comment by ishu-thakur** [comment]
Hi @firaja , I would like to work on this issue .

**Comment by firaja** [comment]
@ishu-thakur assigned.

Remember to check code coverage produced by jacoco.

**Comment by ishu-thakur** [comment]
Hi @firaja i have raised the PR .Please go through it and if any changes required in it , i will be happy to do it :)

**Comment by ishu-thakur** [comment]
Hi @firaja I have debugged the code and i found that while running mvn -X clean test there are two testcase failures in the com.password4j.PasswordTest 
1. testBanner2 = java.lang.AssertionError.
2. testGenericUpdate1 = java.lang.UnsupportedOperationException: `PBKDF2WithHmacSHA256` is not a valid algorithm.
But the weird thing is when I'm running passwordTest test class separately then all testcases passed  .

**Comment by firaja** [comment]
@ishu-thakur Can you please open a new issue with the full stack trace of both failing tests? Thank you.
We will discuss the problem in a different thread so this can be closed once you push the changes requested in PR #98

**Comment by firaja** [comment]
Hi @res13 
The feature will be deployed within the next release (1.7.0).
If you want to use it before the release you can use the version in `master` branch.

**Comment by firaja** [comment]
@res13 the feature is public under version 1.7.0.

You can use `global.salt.length` to define the length of salts.
