### ISSUE TITLE
Please provide byte array based hashing

### ISSUE THREAD

**Issue by scubajorgen** [Password4j/password4j#99]
Thanks for this great project
A problem is that it is not possible to use the hashing based on raw byte arrays.
I tried to use Argon2 hashing with a raw byte array as salt and a password consisting of raw bytes.
(This is the way argon2d and argon2id are used to decrypt Keepass databases)

However it is impossible to insert these arrays. It can only be done by creating a String out of the bytes and then pass the strings. However, under the hood the Strings/CharSequences are converted to bytes again. However some UTF8 decoding takes place, not resulting in the original byte arrays!

It would be great to have a version also including hash functions that take byte arrays as input

**Comment by firaja** [comment]
Hi @scubajorgen,

this is a good feature to implement.
Do you have any example to test where password4j transforms things not as expected?

**Comment by JorgenVanDerVelde** [comment]
> Hi @scubajorgen,
> 
> this is a good feature to implement. Do you have any example to test where password4j transforms things not as expected?

I used password4j Argon2d in my [project to decrypt KeePass databases](https://github.com/scubajorgen/KeepassDecrypt). Did conversion from raw byte[] to String for the seed and password (using various charactersets). However I could not get this working. I suspected the byte[]->String->byte[] conversion based on your source code. Therefore I did a comparison of the result of password4j and BouncyCastle/Spring and they differed.

I made a [quick and dirty copy of your password4j argon function](https://github.com/scubajorgen/KeepassDecrypt/blob/master/src/main/java/net/studioblueplanet/keepassdecrypt/Argon2Function.java) (I hope I did not violate licences)  and removed the String stuff. It worked.

You can use my [unit test](https://github.com/scubajorgen/KeepassDecrypt/blob/master/src/test/java/net/studioblueplanet/keepassdecrypt/Argon2FunctionTest.java), testHashTimed() as a working example.

**Comment by firaja** [comment]
Hi @scubajorgen , @JorgenVanDerVelde 

version 1.7.0 is now public with public APIs accepting `byte[]` arguments.
I used your unit test as example here: https://github.com/Password4j/password4j/blob/master/src/test/com/password4j/PasswordTest.java#L1169

See the [changelog](https://github.com/Password4j/password4j/blob/master/CHANGELOG.md) for further information.

**Comment by scubajorgen** [comment]
Thanx! I tested your software in my code to decrypt Keepass databases and it worked out fine!! Thanks for your great work.
